cmake_minimum_required(VERSION 3.22)
project(rover_motor_driver)
find_package(gz-sim8 REQUIRED)
find_package(gz-plugin2 REQUIRED COMPONENTS register)
find_package(gz-transport13 REQUIRED)
add_library(rover_motor_driver SHARED MotorDriver.cc)
target_compile_features(rover_motor_driver PRIVATE cxx_std_17)
target_compile_options(rover_motor_driver PRIVATE -Wall -Wextra -Werror)
target_link_libraries(rover_motor_driver gz-sim8::gz-sim8 gz-plugin2::register gz-transport13::gz-transport13)
install(TARGETS rover_motor_driver LIBRARY DESTINATION lib)
